// generated 2006/3/17 8:58:42 MST by bda@localhost.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/bda/Projects/blp/blp.glade
// for gtk 2.6.10 and gtkmm 2.6.2
//
// Please modify the corresponding derived classes in ./src/dialogAlert.hh and./src/dialogAlert.cc

#ifndef _DIALOGALERT_GLADE_HH
#  define _DIALOGALERT_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/button.h>
#include <gtkmm/label.h>

class dialogAlert_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Dialog * dialogAlert;
        class Gtk::Button * okbutton1;
        class Gtk::Label * labelAlertText;
protected:
        
        dialogAlert_glade();
        
        ~dialogAlert_glade();
};
#endif
