# generated 2007/3/31 15:15:50 MDT by barcjr@Sirius.(none)
# using glademm V2.6.0
#
# newer (non customized) versions of this file go to Makefile.am_new
bin_PROGRAMS = blproot

blproot_SOURCES = \
	blproot.cc\
	windowBLP_glade.cc \
	windowBLP.cc \
	dialogAlert_glade.cc \
	dialogAlert.cc 

noinst_HEADERS = \
	windowBLP_glade.hh \
	windowBLP.hh \
	dialogAlert_glade.hh \
	dialogAlert.hh 

AM_CXXFLAGS = @GTKMM_CFLAGS@ 

blproot_LDADD = @LIBS@ @GTKMM_LIBS@ 
