// generated 2007/3/31 15:15:50 MDT by barcjr@Sirius.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/barcjr/BLProot/blp.glade
// for gtk 2.8.20 and gtkmm 2.8.8
//
// Please modify the corresponding derived classes in ./src/windowBLP.hh and./src/windowBLP.cc

#ifndef _WINDOWBLP_GLADE_HH
#  define _WINDOWBLP_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/combobox.h>
#include <gtkmm/entry.h>
#include <gtkmm/treeview.h>
#include <gtkmm/statusbar.h>

class windowBLP_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::ComboBox * comboboxLogger;
        class Gtk::ComboBox * comboboxBandMode;
        class Gtk::ComboBox * comboboxOperator;
        class Gtk::Entry * entryCall;
        class Gtk::Entry * entryConClass;
        class Gtk::Entry * entrySection;
        class Gtk::TreeView * treeviewCalls;
        class Gtk::TreeView * treeviewSections;
        class Gtk::Statusbar * statusbarBLP;
protected:
        
        windowBLP_glade();
        
        ~windowBLP_glade();
private:
        virtual void on_new_operator_activate() = 0;
        virtual void on_quit_activate() = 0;
        virtual void on_qso_activate() = 0;
        virtual void on_operator_name_activate() = 0;
        virtual void on_station_activate() = 0;
        virtual void on_history_activate() = 0;
        virtual void on_score_activate() = 0;
        virtual void on_reports_activate() = 0;
        virtual void on_help_activate() = 0;
        virtual void on_about1_activate() = 0;
        virtual void on_comboboxLogger_changed() = 0;
        virtual void on_comboboxBandMode_changed() = 0;
        virtual void on_comboboxOperator_changed() = 0;
        virtual void on_entryCall_changed() = 0;
        virtual bool on_entryCall_focus_out_event(GdkEventFocus *ev) = 0;
        virtual bool on_entryConClass_focus_out_event(GdkEventFocus *ev) = 0;
        virtual void on_entrySection_changed() = 0;
        virtual bool on_entrySection_focus_out_event(GdkEventFocus *ev) = 0;
        virtual void on_treeviewCalls_row_activated(const Gtk::TreeModel::Path& path, Gtk::TreeViewColumn* column) = 0;
        virtual void on_treeviewSections_row_activated(const Gtk::TreeModel::Path& path, Gtk::TreeViewColumn* column) = 0;
        virtual void on_ClearQSO() = 0;
        virtual void on_SaveQSO() = 0;
};
#endif
